// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtNTJG6frFsDVpvvlUkXVilhIS9xpXTJo',
    appId: '1:555565356386:web:68e9147f3fe24350c0083b',
    messagingSenderId: '555565356386',
    projectId: 'bike-rental-app-e2e33',
    authDomain: 'bike-rental-app-e2e33.firebaseapp.com',
    storageBucket: 'bike-rental-app-e2e33.appspot.com',
    measurementId: 'G-PM2WGHRWTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7uGcAi8HdEI8cj6HouZYSyqvWKWyMW8Y',
    appId: '1:555565356386:android:0f8359382aca3e99c0083b',
    messagingSenderId: '555565356386',
    projectId: 'bike-rental-app-e2e33',
    storageBucket: 'bike-rental-app-e2e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOZ4nfjznQFGIlXOQ2OfUlmhAbh-_zREk',
    appId: '1:555565356386:ios:4fd1b90860ff2874c0083b',
    messagingSenderId: '555565356386',
    projectId: 'bike-rental-app-e2e33',
    storageBucket: 'bike-rental-app-e2e33.appspot.com',
    androidClientId: '555565356386-jb4o4j62rkirn80kgcvck3ttm3cqdf5s.apps.googleusercontent.com',
    iosClientId: '555565356386-hv9u4l0suef65p105mreqfidafe5dcf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeappV0',
  );
}
